#!/usr/bin/env python3
"""
build_jee.py
------------
Creates a JEE variant of this Telegram bot WITHOUT modifying the original
JEE source tree.

Usage:
    python build_jee.py
    python build_jee.py /path/to/JeeQuizBot-main /path/to/JeeQuizBot-main
"""

from __future__ import annotations
import os
import shutil
import sys
from pathlib import Path

DEFAULT_SOURCE = Path(__file__).resolve().parent
DEFAULT_OUTPUT = DEFAULT_SOURCE.parent / "JeeQuizBot-main"

# Ordered replacements: specific phrases first, then general replacements.
REPLACEMENTS = [
    # Bot / channel branding
    ("@JeeQuizRobotUpdates", "@JeeQuizRobotUpdates"),
    ("JeeQuizRobotUpdates", "JeeQuizRobotUpdates"),
    ("@JeeQuizRobot", "@JeeQuizRobot"),
    ("JeeQuizRobot", "JeeQuizRobot"),

    # Existing mixed branding should not become "JEE & JEE".
    ("Jee", "Jee"),
    ("JEE", "JEE"),
    ("JEE", "JEE"),
    ("Jee", "Jee"),

    # More specific educational wording.
    ("engineering entrance exams", "engineering entrance exams"),
    ("Engineering entrance exams", "Engineering entrance exams"),
    ("engineering entrance", "engineering entrance"),
    ("Engineering entrance", "Engineering entrance"),

    # General JEE -> JEE, preserving common casing.
    ("JEE", "JEE"),
    ("Jee", "Jee"),
    ("jee", "jee"),
]

# Binary/generated files that should not be copied into the build.
SKIP_DIRS = {
    "__pycache__", ".git", ".pytest_cache", ".mypy_cache", ".ruff_cache"
}
SKIP_SUFFIXES = {
    ".pyc", ".pyo"
}

# Only these text-like files are rewritten. Other assets are copied byte-for-byte.
TEXT_SUFFIXES = {
    ".py", ".md", ".txt", ".json", ".toml", ".ini", ".cfg", ".yaml", ".yml",
    ".replit", ".env", ".html", ".css", ".js", ".ts"
}

def should_skip(path: Path, source: Path) -> bool:
    rel = path.relative_to(source)
    if any(part in SKIP_DIRS for part in rel.parts):
        return True
    if path.is_file() and path.suffix.lower() in SKIP_SUFFIXES:
        return True
    return False

def rewrite_text(text: str) -> str:
    for old, new in REPLACEMENTS:
        text = text.replace(old, new)
    return text

def build(source: Path, output: Path) -> None:
    source = source.resolve()
    output = output.resolve()

    if not source.exists() or not source.is_dir():
        raise SystemExit(f"Source directory not found: {source}")

    if output == source:
        raise SystemExit("Refusing to use the source directory as output.")

    if output.exists():
        shutil.rmtree(output)

    output.mkdir(parents=True)

    changed = 0
    copied = 0

    for src in source.rglob("*"):
        if should_skip(src, source):
            continue

        rel = src.relative_to(source)
        dst = output / rel

        if src.is_dir():
            dst.mkdir(parents=True, exist_ok=True)
            continue

        dst.parent.mkdir(parents=True, exist_ok=True)

        if src.suffix.lower() in TEXT_SUFFIXES or src.name in {".replit"}:
            try:
                text = src.read_text(encoding="utf-8")
                new_text = rewrite_text(text)
                dst.write_text(new_text, encoding="utf-8")
                copied += 1
                if new_text != text:
                    changed += 1
            except UnicodeDecodeError:
                shutil.copy2(src, dst)
                copied += 1
        else:
            shutil.copy2(src, dst)
            copied += 1

    # Keep the generated project self-identifying.
    build_note = output / "JEE_BUILD_INFO.txt"
    build_note.write_text(
        "Generated by build_jee.py\n"
        "Original JEE source was not modified.\n"
        "Primary bot: @JeeQuizRobot\n"
        "Updates channel: @JeeQuizRobotUpdates\n",
        encoding="utf-8",
    )

    print("========================================")
    print(" JEE BUILD CREATED SUCCESSFULLY")
    print("========================================")
    print(f"Source : {source}")
    print(f"Output : {output}")
    print(f"Files copied : {copied}")
    print(f"Text files rewritten : {changed}")
    print()
    print("Original JEE project was NOT modified.")
    print("JEE bot branding: @JeeQuizRobot")
    print("JEE updates:      @JeeQuizRobotUpdates")
    print()
    print("Next:")
    print(f"  cd {output}")
    print("  python main.py")

if __name__ == "__main__":
    src = Path(sys.argv[1]).expanduser() if len(sys.argv) > 1 else DEFAULT_SOURCE
    out = Path(sys.argv[2]).expanduser() if len(sys.argv) > 2 else DEFAULT_OUTPUT
    build(src, out)
